# Generated by Django 2.1.1 on 2018-09-16 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_mine', models.PositiveIntegerField(default=1)),
                ('rock_mine', models.PositiveIntegerField(default=1)),
                ('lumber_camp', models.PositiveIntegerField(default=1)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='gold_production',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rock_production',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='resource',
            name='wood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='wood_production',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
