# Generated by Django 2.1.1 on 2018-09-17 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='enemy_id',
        ),
        migrations.AddField(
            model_name='attack',
            name='enemy_id',
            field=models.ManyToManyField(blank=True, related_name='enemy_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
