# Generated by Django 2.1.1 on 2018-09-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_auto_20180917_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='enemy_id',
        ),
        migrations.AddField(
            model_name='attack',
            name='enemy_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enemy_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
