# Generated by Django 2.1.1 on 2018-09-18 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20180917_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('enemy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_enemy_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='attack',
            name='enemy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_enemy_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
