# Generated by Django 2.1.1 on 2018-09-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180918_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='gold',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rock',
            field=models.PositiveIntegerField(default=150000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='wood',
            field=models.PositiveIntegerField(default=350000),
        ),
    ]
