# Generated by Django 2.1.1 on 2018-09-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180918_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='gold',
            field=models.PositiveIntegerField(default=75000),
        ),
    ]
